### ISSUE TITLE
Implement bullet and enemy collision (damage system & HP)

### ISSUE THREAD

**Issue by davcri** [crystal-bit/space-shooter#11]
Once #9 and #8 are done: implement a simple damage system:

- Update `Enemy1.gd`:
   1. Add `hp` variable
   2. Add a `takeDamage(damage)` function
   3. The `takeDamage` function should reduce the `hp` amount and emit a signal `defeated` when the enemy's `hp` are less or equal to zero.
   4. If the enemy is defeated, remove the `Enemy1` node from the scene (free memory)

- When a bullet hits an enemy:
   1. Destroy the bullet
   2. Remove a certain amount of HP from the enemy instance calling the `takeDamage` function

**Comment by ManuelPepe129** [comment]
Working on it
