### ISSUE TITLE
Create custom icon for the game

### ISSUE THREAD

**Issue by davcri** [crystal-bit/space-shooter#19]
Create a small icon for the game.

It would be nice to have something similar to the logo that will be implemented in #18.

Set the icon as a project icon so that Godot will show it in the project list:
![Screenshot_20191001_174917](https://user-images.githubusercontent.com/6860637/65978646-60a0c900-e474-11e9-9e2c-3f4a39482dce.png)

**Comment by woody889** [comment]
Hi i'm ita and i want to contribute to the project with this icon that i've made with paint.net
![icon](https://user-images.githubusercontent.com/56045946/65991660-f9900e00-e48d-11e9-95cd-01db6a36c8ba.png)

**Comment by woody889** [comment]
hi i'm italian and i've made the custom icon for the game ;)
![icon](https://user-images.githubusercontent.com/56045946/65993029-aec3c580-e490-11e9-95b6-e5681512e6c4.png)

**Comment by davcri** [comment]
Not bad at all! I like it :D Also with rounded corners ;) 

If you want to get the PR recognized by Github (for the Hacktoberfest event), you need to:

1. create a fork of the project
2. upload the image to your fork
3. create a pull request

You should be able to do this using Github with the web browser.

If you don't care for the Hacktoberfest, I can add the icon for you :) Let me know!

**Comment by davcri** [comment]
Closed by #31
