### ISSUE TITLE
Add logo in the main screen

### ISSUE THREAD

**Issue by davcri** [crystal-bit/space-shooter#20]
After logo is created in #18, add the logo in the main screen.

*[Optional]*:
- [ ] Animate the logo apparition using the AnimationPlayer

**Comment by Karbb** [comment]
I'm doing this

**Comment by davcri** [comment]
Are you creating also the logo? (https://github.com/crystal-bit/space-shooter/issues/18)

**Comment by Karbb** [comment]
Yep. I'm trying to do it
