### ISSUE TITLE
Implement enemy spawn

### ISSUE THREAD

**Issue by davcri** [crystal-bit/space-shooter#30]
Now that we have an enemy scene (see #25), we can implement a spawn system for the enemies.

We need a script that:

1.Creates a new instance of the `Enemy1.tscn`
3. Has a constant variable called `MAX_AMOUNT_OF_ENEMIES` with value 5
4. Stops spawning if there are more than `MAX_AMOUNT_OF_ENEMIES` 

[*Optional*]:
- [x] Enemies are spawned on the right side of the screen (they don't need to move after they spawned, we will do this in another issue)
- [x] The script has an exported variable and you can drag&drop a scene into it (hint: see `export` keyword)

---

Note: feel free to remove the GUI elements that you see in the right side of *Level1* scene.

![Screenshot_20191002_195721](https://user-images.githubusercontent.com/6860637/66069290-599ab900-e54f-11e9-8280-079a9ffcc8df.png)

**Comment by Derek52** [comment]
Can I take this issue?

**Comment by davcri** [comment]
Sure @Derek52 :smiley:

**Comment by Derek52** [comment]
Instead of a script, can I make an enemy spawning node? The node could be positioned wherever an enemy should spawn, and new enemies could spawn at the spawner's position.

**Comment by davcri** [comment]
Done in #33
