### ISSUE TITLE
Integrate EnemySpawen in Level1 scene

### ISSUE THREAD

**Issue by davcri** [crystal-bit/space-shooter#38]
In #33 we got a EnemySpawner node. We want to integrate it into the `Level1` scene.

Things that we probably need to do:

- Fix the enemy spawn position
- Fix the enemy scale

**Comment by woody889** [comment]
i'm working on this ;)

**Comment by davcri** [comment]
@woody889 there was already a [a pull request](https://github.com/crystal-bit/space-shooter/pull/40) by @Marco-2188 for this one. He forgot to comment here unfortunately.

Woody thanks for your help and feel free to take another issue :)
