### ISSUE TITLE
Implement spaceship movement

### ISSUE THREAD

**Issue by davcri** [crystal-bit/space-shooter#4]
- Update the [spaceship script](https://github.com/crystal-bit/space-shooter/blob/master/Scenes/Spaceship/Spaceship.gd) to move the spaceship when the user presses the W, A, S, D keys
- Spaceship movement should be frame independent
- Make sure that the spaceship moves correctly in the `Gameplay/Level1.tscn scene`

**Comment by Hairic95** [comment]
Created a basic movement system at #21, that uses a Node to check key inputs (one per key), to be developed to implement button clicks and gamepad input as well and by being flexible to key rebinding

**Comment by Ciaocrystalbit** [comment]
With this, the scace ship continue movinging on the right, but with WASD you can change position and you only need to lock camera on the ship, i think ( i the first time i write something, sorry if is not good).


func _ready():
	print(" vediamo se funziona qualche cosa, o non ho capito un c***o")
	print(self.position)
	self.position.x = 100

var b = 1

# Called every frame. 'delta' is the elapsed time since the previous frame.
func _process(delta):
	
	
	
	var velocita = Vector2(b,0)
	
	if Input.is_key_pressed(KEY_W):    # i seguenti sono tutti comandi per il movimento dove su self position y ed x sono i punti degli assi che cambiano
		velocita.y = -1
	if Input.is_key_pressed(KEY_S):
		velocita.y = 1
	if Input.is_key_pressed(KEY_A):
		velocita.x = -1
	if Input.is_key_pressed(KEY_D):
		velocita.x = 1
		
		
	print(delta)
	
	self.position = self.position + velocita.normalized()*300*delta

**Comment by davcri** [comment]
Thanks @Hairic95 and @Ciaocrystalbit !

@Ciaocrystalbit : I'm going to update the markdown formatting of your post so that is easier for others to read!
