### ISSUE TITLE
Implement Enemy1 movement

### ISSUE THREAD

**Issue by davcri** [crystal-bit/space-shooter#44]
This issue is 50% game design and 50% game programming. Feel free to split it up if you prefer.

1. Define how enemy1 should spawn and move. Take a look at the current GDD and feel free to update it: https://github.com/crystal-bit/space-shooter/blob/master/game-design-doc/game-design-document.md#enemy-spawn
2. Implement enemy movement

For the first point, you can take inspiration from here: [Gradius III gameplay video](https://youtu.be/pjQ1_8hbp9I?t=30)

**Comment by Marco-2188** [comment]
I work on this

**Comment by davcri** [comment]
Thanks @Marco-2188 ! Looking forward to this!
