### ISSUE TITLE
Implement bullet and player spaceship collision (damage system & HP)

### ISSUE THREAD

**Issue by davcri** [crystal-bit/space-shooter#45]
Add collision detection for bullets of the enemies and player.

Please read the GDD for more information: https://github.com/crystal-bit/space-shooter/blob/master/game-design-doc/game-design-document.md#spaceship---receive-damage

### Notes
- Similar to #11
- You don't need to use any state machine pattern to implement this but feel free to do it if you are comfortable with it.
- Implementing health icons is not part of this issue! See #47

**Comment by Karbb** [comment]
MINE!

I SAID MINE! 

workin' on it

**Comment by davcri** [comment]
![Screenshot_20191015_154110](https://user-images.githubusercontent.com/6860637/66853727-3d037580-ef80-11e9-85c4-655104e70087.png)
