### ISSUE TITLE
Implement a GUI for the player's spaceship HP/Life

### ISSUE THREAD

**Issue by davcri** [crystal-bit/space-shooter#47]
After #46 is done, implement a GUI for the spaceship HP.

We want to implement a simple lives system like the one in Gradius:

![Screenshot_20191006_161018](https://user-images.githubusercontent.com/6860637/66270462-41c77b80-e854-11e9-88c2-a0706cc64d5e.png)
- Gameplay video: https://youtu.be/WnKk3VWigKs?t=2234
- Please read [Spaceship Life in the GDD](https://github.com/crystal-bit/space-shooter/blob/master/game-design-doc/game-design-document.md#spaceship-life) for additional info

**Comment by Derek52** [comment]
I'll go ahead and take this. If #45 isn't done I'll just insert a placeholder image for someone else to swap out.

**Comment by davcri** [comment]
Great! Thanks @Derek52 !
