### ISSUE TITLE
Implement Enemy1 fire bullet mechanic

### ISSUE THREAD

**Issue by davcri** [crystal-bit/space-shooter#48]
Define the Enemy1 logic to shoot bullets towards the player.

There is no defined behaviour in the GDD at the moment, so feel free to create one by yourself. 

If you are uncertain, I would say that shooting after a random amount of seconds between 0.5 and 2 is fine.

[*Optional*]
- [ ] Update the GDD: https://github.com/crystal-bit/space-shooter/blob/master/game-design-doc/game-design-document.md#enemy-1

**Comment by SONOMNT7** [comment]
I'm now implementing this

**Comment by SONOMNT7** [comment]
almost finished

**Comment by SONOMNT7** [comment]
I'm uploadig
