### ISSUE TITLE
Load Level1 on "Start game" button pressed

### ISSUE THREAD

**Issue by davcri** [crystal-bit/space-shooter#5]
We want to update the behaviour to load the Level1 scene (`/Scenes/Gameplay/Level1/Level1.tscn`). At the moment if you press the "Start Game" button nothing happens. 

[_Optional_]: it would be nice to add the `SceneManager` script as an autoload: https://github.com/crystal-bit/triple-triad-godot/blob/master/Globals/SceneManager/SceneManager.gd

**Comment by therealwayan** [comment]
I'm working on this issue, I've managed to load the scene and now I'm working on adding the "SceneManager" script.

**Comment by ntieman** [comment]
Going to take a quick stab at this.

**Comment by ntieman** [comment]
Got a PR:
https://github.com/crystal-bit/space-shooter/pull/32
