### ISSUE TITLE
Swap battle and menu musics?

### ISSUE THREAD

**Issue by davcri** [crystal-bit/space-shooter#54]
Thanks to @MaxGameDev and @woody889  we have 2 songs for this game:

1. https://github.com/crystal-bit/space-shooter/blob/master/Music/Menu%20Theme.ogg
2. https://github.com/crystal-bit/space-shooter/blob/master/Assets/gameplay_music.ogg

I feel like song 1 has a good mood for the gameplay part and song 2 has adapts better for the main menu. 

What do you think? I was thinking about swapping the 2 songs.

**Comment by Karbb** [comment]
Yep. It sounds a good idea, but we also need a volume slider or a mute button

**Comment by davcri** [comment]
Yeah definitely!

Issue for the volume slider: https://github.com/crystal-bit/space-shooter/issues/60

**Comment by Karbb** [comment]
Done in #73
