### ISSUE TITLE
Create bullet scene

### ISSUE THREAD

**Issue by davcri** [crystal-bit/space-shooter#6]
Create a new scene for the bullet. The bullet will be fired by the spaceship (implemented in another issue).

For the sprite you can use the ones in `Assets/warped city files/sprites/misc/shot/` or you can draw one yourself.

Nice to have:
- Looping sprite animation instead of a static sprite
- Nodes for collision detecion:`Aread2D` and a `CollisionShape`

**Comment by ManuelPepe129** [comment]
Working on this issue
