### ISSUE TITLE
Make the volume slider work

### ISSUE THREAD

**Issue by davcri** [crystal-bit/space-shooter#60]
In the `OptionsSubmenu` scene we have a volume slider: add the code to make Godot set the volume of all sounds according to the slider percentage.

Tip: use the audio Bus
 
![Screenshot_20191009_201644](https://user-images.githubusercontent.com/6860637/66508598-b9560e80-ead1-11e9-91f5-be211e25cbae.png)

**Comment by Karbb** [comment]
Working on it 🎵
