### ISSUE TITLE
Create signal "gameover"  in the Spaceship scene

### ISSUE THREAD

**Issue by davcri** [crystal-bit/space-shooter#75]
We want to add gameover mechnic to the game when the player runs out of lives.

In the spaceship scene:

- Add a `gameover` signal 
- Dispatch the signal when the spaceship finishes its lives

We will handle the gameover screen and the spaceship destruction in another issue.

**Comment by Karbb** [comment]
Doing this

**Comment by Karbb** [comment]
While I was reading the code, I found out this feature exists already.

HUD script lines 3 and 43

**Comment by davcri** [comment]
Thanks @Karbb! Closing this!
