### ISSUE TITLE
Create Spaceship explosion scene

### ISSUE THREAD

**Issue by davcri** [crystal-bit/space-shooter#76]
When the spaceship finishes its lives, we want to add an explosion scene to the game and then dispatch the gameover screen.

For this issue we want:

- Create a separate scene for the explosion. 
- Nodes & assets for the graphic effect of the explosion (you have freedom here: particles, sprite animations, shaders, ...)
- Nodes & assets for the sound effect of the explosion

**Comment by davcri** [comment]
If this issue seems like too much work, feel free to split it into multiple issue!

**Comment by Karbb** [comment]
I closed this in PR #91
