### ISSUE TITLE
Implement "fire bullet" mechanic

### ISSUE THREAD

**Issue by davcri** [crystal-bit/space-shooter#8]
After #6 is done, implement the fire bullet mechanic described below:

1. When the user presses the `J` key
   1. Create an instance of the bullet in the current position of the spaceship
   2. Apply the bullet velocity (Vector2 with a positive x value)

[*Optional*]:
- [ ] Define a variable for the bullet speed and export it to be visible in the editor
- [ ] Detect when the bullet is out of the screen and destroy it (to avoid waste of memory)
- [ ] Define a "fire rate": the user should fire only a certain amount of bullets per second

**Comment by Karbb** [comment]
I'm working on this

**Comment by davcri** [comment]
Thanks @Karbb :smile:
