### ISSUE TITLE
Pick powerup on Spaceship collision

### ISSUE THREAD

**Issue by davcri** [crystal-bit/space-shooter#85]
When the Spaceship intersects with a Powerup:

1. Remove the powerup from the scene
2. Activate the powerup effect (see: https://github.com/crystal-bit/space-shooter/blob/master/game-design-doc/game-design-document.md#fire-bullet---powerup1)
3. Deactivate the powerup after 15 seconds

Feel free to implement a different behaviour for the powerup. It would be nice to update the GDD as well in this case.

**Comment by ManuelPepe129** [comment]
I'll do It

**Comment by FlavioFS** [comment]
Since I've made it disappear in issue 86 (#99), it kinda overlapped with this issue 85.
So I did it too, sorry for medling in your stuff @ManuelPepe129 😅
