### ISSUE TITLE
Create powerup pick sound effect

### ISSUE THREAD

**Issue by davcri** [crystal-bit/space-shooter#86]
Do this after #85.
 
When the player takes a powerup, we want to play a sound effect.

1. Create a sound effect
2. Add it to the game
3. Play the sound effect on Spaceship and powerup collision

**Comment by FlavioFS** [comment]
I did it.
Submitting pull request right now.

**Comment by FlavioFS** [comment]
PR submitted.

**Comment by davcri** [comment]
PR accepted!
