### ISSUE TITLE
Create enemy1 scene 

### ISSUE THREAD

**Issue by davcri** [crystal-bit/space-shooter#9]
Create a new scene for the first enemy. The enemy will be spawned in the Level by the another script (implemented in another issue).

For the sprite you can use the ones in `Assets/warped city files/sprites/vehicles/` or you can draw one yourself.

[*Optional*]
- [x] Add nodes for collision detecion: Aread2D and a CollisionShape
- [x] Add an empty `Enemy1.gd` script to the root node of the scene (it will be used to add enemy attributes like HP, damage dealt etc.)

**Comment by ManuelPepe129** [comment]
I'm working on this issue

**Comment by davcri** [comment]
Great work @ManuelPepe129!
